version: '3.8'

networks:
  app-network:
    external: true  # Ensure it connects to the same network as other services

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the nginx.conf from the host
      - ./nginx/conf.d:/etc/nginx/conf.d    # Mount any additional config from conf.d folder
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - certbot
    networks:
      - app-network


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; certbot renew; done'"  # Auto renew certificates
    networks:
      - app-network
